# Generated by Django 2.1.4 on 2018-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam',
            field=models.CharField(default='https://store.steampowered.com/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(default='https://steamstore-a.akamaihd.net/public/shared/images/responsive/share_steam_logo.png', max_length=1000),
        ),
    ]
