# Generated by Django 2.1.4 on 2019-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20190123_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='arcade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cartoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_builder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_based',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='twod',
            field=models.IntegerField(default=0),
        ),
    ]
