# Generated by Django 2.1.4 on 2019-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20190123_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clip',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='streams',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
